package com.bank.bian.prospectcampaigndesign;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Prospect Campaign Design
 *
 * Business Area:      Sales and Service
 * Business Domain:    Sales
 * Functional Pattern: Design
 * Asset Type:         Prospect Campaign
 * Control Record:     Prospect Campaign Design
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Prospect Campaign Design — BIAN Semantic API")
                .description("Service Domain 'Prospect Campaign Design' (Design pattern) "
                        + "operating on the 'Prospect Campaign Design' control record.")
                .version("0.1.0"));
    }
}
