apiVersion: v2
name: sd-prospect-campaign-design
description: "BIAN Service Domain: Prospect Campaign Design (Design pattern, Sales and Service)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - design
annotations:
  bian/business-area: "Sales and Service"
  bian/business-domain: "Sales"
  bian/asset-type: "Prospect Campaign"
  bian/control-record: "Prospect Campaign Design"
